spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  validityDuration: ${JWT_VALIDITY_DURATION}

springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs

server:
  error:
    include-message: always